version: '3'

services:
  logsdb:
    image: postgres
    container_name: servicelogdb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: "Asia/Bangkok"
    ports:
      - "35432:5432"
    volumes:
      - my-db:/var/lib/postgresql/data

  logservice:
    build: ./
    container_name: servicelog
    environment:
      - TZ: "Asia/Bangkok"
    env_file:
      - .env
    ports:
      - "30000:30000"
    depends_on:
      - logsdb
    # volumes:
    #   - ./:/usr/src/app

volumes:
  my-db: